### PR TITLE
Add template tests (and fix existing)

### PR DESCRIPTION
**Pull request by djmarcin**
This also refactors the template expansion logic into the `shared.bash` file.

There is one minor change to the expansion logic which is that instead of `checksum` needing to appear anywhere inside the template, it is required to appear at the front. The regex strips leading spaces (although not tabs) already, so it should be OK to demand that `checksum` appears first. This is technically a breaking change but like the other it seems unlikely anyone would be relying on this.

The other behavior was problematic because the "should fail" test didn't fail since the path of the file included "checksum".

### CODE REVIEW

**Comment by gencer** [comment]
Great improvements here. Thanks!

Just one question. I believe when Buildkite triggers a job, `lib/shared.bash` could not be found due to pwd issues. Don't you think we should use: `source "$CURRENT_DIR/../lib/shared.bash"`?

**Comment by djmarcin** [comment]
Hmm, I’m not sure, maybe. Is there a way to test the plugin from my fork? I
only tested it using the docker container.

**Comment by gencer** [comment]
I believe it will not work because as you can see 2 lines above I've included `VERSION` file. That is the reason I made `$CURRENT_DIR` variable in the first place.

The reason is, Buildkite runs this hook directly on `/` main directory. So we need to find `bash_source` then find the required files.

**Comment by djmarcin** [comment]
Updated to reference the plugin root directory. The tests still work locally.

**Comment by gencer** [comment]
🎉 Great! I will also setup a buildkite pipeline for the tests to show status.

**Comment by gencer** [comment]
🎉 Great! I will also setup a buildkite pipeline for the tests to show status.

Thank you so much for the contributions!

**Comment by gencer** [comment]
@djmarcin I just wanted to let you know that, shellcheck and tests are failed on bk. However, I've fixed shellcheck issues. Tests ultimately shows errors on s3 side. I'm attaching the output here:

```

✗ Pre-command restores cache with basic key
--
  | (from function `assert_output' in file /usr/local/lib/bats/bats-assert/src/assert.bash, line 231,
  | in test file tests/command.bats, line 26)
  | `assert_output --partial "Copied from S3"' failed
  |  
  | -- output does not contain substring --
  | substring (1 lines):
  | Copied from S3
  | output (5 lines):
  | ~~~ :bash: Initializing Cache Buildkite Plugin v2.0.10
  | 🔍 Looking for v1-cache-key
  | 🔍 Locating cache on S3
  | 🔥 Cache hit: s3://my-bucket/my-org/my-pipeline/v1-cache-key.tar
  | Extracted tar archive
  | --
  |  
  | ✗ Post-command syncs artifacts with a single path
  | (from function `assert_output' in file /usr/local/lib/bats/bats-assert/src/assert.bash, line 231,
  | in test file tests/command.bats, line 63)
  | `assert_output --partial "Copied to S3"' failed
  |  
  | -- output does not contain substring --
  | substring (1 lines):
  | Copied to S3
  | output (3 lines):
  | ~~~ :bash: Processing Post-Cache...
  | 🔍 Locating cache on S3: Pods
  | Created tar archive
  | --
  |  
  | ✗ Cache key template evaluation on file
  | (from function `assert_output' in file /usr/local/lib/bats/bats-assert/src/assert.bash, line 231,
  | in test file tests/command.bats, line 99)
  | `assert_output --partial "Copied from S3"' failed
  |  
  | -- output does not contain substring --
  | substring (1 lines):
  | Copied from S3
  | output (5 lines):
  | ~~~ :bash: Initializing Cache Buildkite Plugin v2.0.10
  | 🔍 Looking for v1-cache-key-355831032f586e782b45744f2ed79316cc830244
  | 🔍 Locating cache on S3
  | 🔥 Cache hit: s3://my-bucket/my-org/my-pipeline/v1-cache-key-355831032f586e782b45744f2ed79316cc830244.tar
  | Extracted tar archive
  | --
  |  
  | ✗ Cache key template evaluation on dir
  | (from function `assert_output' in file /usr/local/lib/bats/bats-assert/src/assert.bash, line 231,
  | in test file tests/command.bats, line 132)
  | `assert_output --partial "Copied from S3"' failed
  |  
  | -- output does not contain substring --
  | substring (1 lines):
  | Copied from S3
  | output (5 lines):
  | ~~~ :bash: Initializing Cache Buildkite Plugin v2.0.10
  | 🔍 Looking for v1-cache-key-4cfa4e590847976f26d761074e355e4d95fa8107
  | 🔍 Locating cache on S3
  | 🔥 Cache hit: s3://my-bucket/my-org/my-pipeline/v1-cache-key-4cfa4e590847976f26d761074e355e4d95fa8107.tar
  | Extracted tar archive
  | --
  |  
  | ✗ Cache key multi-template evaluation
  | (from function `assert_output' in file /usr/local/lib/bats/bats-assert/src/assert.bash, line 231,
  | in test file tests/command.bats, line 165)
  | `assert_output --partial "Copied from S3"' failed
  |  
  | -- output does not contain substring --
  | substring (1 lines):
  | Copied from S3
  | output (5 lines):
  | ~~~ :bash: Initializing Cache Buildkite Plugin v2.0.10
  | 🔍 Looking for v1-cache-key-355831032f586e782b45744f2ed79316cc830244-241bc31c8ddc004c48e6d88d7fa51ee981b8ce51
  | 🔍 Locating cache on S3
  | 🔥 Cache hit: s3://my-bucket/my-org/my-pipeline/v1-cache-key-355831032f586e782b45744f2ed79316cc830244-241bc31c8ddc004c48e6d88d7fa51ee981b8ce51.tar
  | Extracted tar archive
  | --
  |  
  | ✗ Cache key template evaluation in middle of key
  | (from function `assert_output' in file /usr/local/lib/bats/bats-assert/src/assert.bash, line 231,
  | in test file tests/command.bats, line 198)
  | `assert_output --partial "Copied from S3"' failed
  |  
  | -- output does not contain substring --
  | substring (1 lines):
  | Copied from S3
  | output (5 lines):
  | ~~~ :bash: Initializing Cache Buildkite Plugin v2.0.10
  | 🔍 Looking for v1-cache-355831032f586e782b45744f2ed79316cc830244-key
  | 🔍 Locating cache on S3
  | 🔥 Cache hit: s3://my-bucket/my-org/my-pipeline/v1-cache-355831032f586e782b45744f2ed79316cc830244-key.tar
  | Extracted tar archive
  | --
  |  
  | ✓ Cache key failed template evaluation fails
  |  
  | 7 tests, 6 failures


```

**Comment by gencer** [comment]
Ok. I've fixed the tests too. 👌

**Pull request merged**
