### PR TITLE
Create tar file atomically

### LINKED ISSUE #6: Concurrent writers to tar files clobber each other
The behavior of `tar cf` when the destination file already exists is to open the file and overwrite the contents. This means that if another agent is concurrently attempting to read this file, it may fail with an error like `tar: Unexpected EOF in archive`.

To prevent this, `tar cf` should use a file created by `mktemp` and then `mv` the file to replace the existing archive atomically.

### PR DESCRIPTION
**Pull request by djmarcin**
I believe this should fix https://github.com/gencer/cache-buildkite-plugin/issues/6

### CODE REVIEW

**Comment by gencer** [comment]
Thanks for the PR! 🎉

One question. Shouldn't we also use `-f` option on `mv`? Because if target exists, it will prompt for the overwrite operation I believe. Please correct me If I'm wrong on this.

```
$ mv --help
...
  -f, --force                  do not prompt before overwriting
...
```

**Comment by djmarcin** [comment]
It doesn't hurt, but I thought mv only prompted if you used `mv -i`. Added.

**Comment by gencer** [comment]
Thanks for the update!

**Comment by djmarcin** [comment]
Tested the tarball storage path using #master 👍

**Comment by gencer** [comment]
Thanks for the confirmation. I believe you tested against macOS, right? So I want to test it on Linux. However, I am pretty sure it will be OK on Linux too. As both works at similar level.

**Comment by djmarcin** [comment]
I have builds running on both macOS and Linux :)

**Comment by gencer** [comment]
Thanks for the re-confirmation @djmarcin! I am releasing a new version now.

**Pull request merged**
